### ISSUE TITLE
Workaround with WordPress upload

### ISSUE THREAD

**Issue by ViliamKopecky** [ktstudio/WP-Tracy#2]
For IE compatibility WordPress media upload declares HTML content type, but sends JSON. And Tracy then outputs itself after, and it f*cks uploading from administration up.

This works for me:

``` php
if(defined('DOING_AJAX') && DOING_AJAX) {
    Tracy\Debugger::$productionMode = TRUE;
}
```

**Comment by hlavacm** [comment]
OK, thanks for the tip, I added it ... :)
